# Generated by Django 3.2.9 on 2021-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_financial_information',
            fields=[
                ('PAN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('GSTIN', models.CharField(max_length=15)),
                ('IFSC', models.CharField(max_length=45)),
                ('account_number', models.CharField(max_length=45)),
                ('beneficiary_name', models.CharField(max_length=45)),
                ('KYC', models.CharField(max_length=45)),
                ('UPI', models.CharField(max_length=45, null=True)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
