# Generated by Django 3.2.9 on 2022-01-01 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='debit_card',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('dcard_number', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('provider', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('ccard_number', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('provider', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='business_financial_information',
            fields=[
                ('PAN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('GSTIN', models.CharField(max_length=15)),
                ('IFSC', models.CharField(max_length=45)),
                ('account_number', models.CharField(max_length=45)),
                ('beneficiary_name', models.CharField(max_length=45)),
                ('KYC', models.CharField(max_length=45)),
                ('UPI', models.CharField(max_length=45, null=True)),
                ('verified', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
