# Generated by Django 3.2.9 on 2022-03-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='retinvt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='retproddtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('sellprice', models.CharField(max_length=5, null=True)),
                ('packed_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_packed')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.retinvt')),
            ],
        ),
        migrations.AddField(
            model_name='retinvt',
            name='packed_products',
            field=models.ManyToManyField(blank=True, null=True, through='retailer.retproddtl', to='products.Product_packed'),
        ),
        migrations.AddField(
            model_name='retinvt',
            name='unpacked_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product_unpacked'),
        ),
        migrations.AddField(
            model_name='retinvt',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='retbi',
            fields=[
                ('pan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gstin', models.CharField(max_length=15)),
                ('ifsc', models.CharField(max_length=45)),
                ('account_number', models.CharField(max_length=45)),
                ('beneficiary_name', models.CharField(max_length=45)),
                ('kyc', models.CharField(default=False, max_length=45)),
                ('upi', models.CharField(max_length=45, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('retailer_business_info_complete', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
