# Generated by Django 3.2.9 on 2022-01-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_financial_information',
            name='KYC',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='business_financial_information',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
