# Generated by Django 3.2.9 on 2022-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_auto_20220109_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_financial_information',
            name='retailer_business_info_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit_card',
            name='retailer_ccard_info_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debit_card',
            name='retailer_dcard_table_complete',
            field=models.BooleanField(default=False),
        ),
    ]
