# Generated by Django 3.2.9 on 2022-01-24 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220124_1634'),
        ('retailer', '0003_auto_20220113_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='retailer_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed_products', models.ManyToManyField(to='products.Product_packed')),
                ('unpacked_products', models.ManyToManyField(to='products.Product_unpacked')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
