# Generated by Django 3.2.9 on 2022-01-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220128_2345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailer', '0004_retailer_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer_inventory',
            name='packed_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product_packed'),
        ),
        migrations.AlterField(
            model_name='retailer_inventory',
            name='unpacked_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product_unpacked'),
        ),
        migrations.CreateModel(
            name='retailer_order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed_products', models.ManyToManyField(blank=True, null=True, to='products.Product_packed')),
                ('unpacked_products', models.ManyToManyField(blank=True, null=True, to='products.Product_unpacked')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
