# Generated by Django 3.2.9 on 2022-03-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wslbi',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser', unique=True)),
                ('pan', models.CharField(max_length=10)),
                ('gstin', models.CharField(max_length=15)),
                ('ifsc', models.CharField(max_length=45)),
                ('account_number', models.CharField(max_length=45)),
                ('beneficiary_name', models.CharField(max_length=45)),
                ('kyc', models.CharField(default=False, max_length=45)),
                ('upi', models.CharField(max_length=45, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('retailer_business_info_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='wslinvt',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='wslproddtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('sellprice', models.CharField(max_length=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_packed')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaler.wslinvt')),
            ],
        ),
        migrations.AddField(
            model_name='wslinvt',
            name='packed_products',
            field=models.ManyToManyField(null=True, through='wholesaler.wslproddtl', to='products.Product_packed'),
        ),
        migrations.AddField(
            model_name='wslinvt',
            name='unpacked_products',
            field=models.ManyToManyField(null=True, to='products.Product_unpacked'),
        ),
        migrations.CreateModel(
            name='wslbrd',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser', unique=True)),
                ('brands', models.ManyToManyField(to='products.Brand')),
            ],
        ),
    ]
