# Generated by Django 3.2.9 on 2022-01-20 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e9870ffb-0a93-4a68-b27a-dab3e771289f'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_unpacked',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2775dbd7-3b30-4082-8708-f51d9d0bddd4'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=40)),
                ('hsn_code', models.CharField(max_length=45)),
                ('cgst', models.CharField(max_length=40)),
                ('sgst', models.CharField(max_length=40)),
                ('igst', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('dozen', 'dozen'), ('gm', 'gm'), ('litre', 'litre'), ('ml', 'ml'), ('inch', 'inch'), ('meter', 'meter'), ('feet', 'feet'), ('nag', 'nag')], max_length=40)),
                ('rate', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product_packed',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('44a90244-bf32-4c1a-86ce-dab3198040f1'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('mrp', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('hsn_code', models.CharField(max_length=45)),
                ('cgst', models.CharField(max_length=40)),
                ('sgst', models.CharField(max_length=40)),
                ('igst', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
    ]
