# Generated by Django 3.2.9 on 2022-01-24 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e12ea3a-019b-49d4-9732-f8fdd4daf600'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_packed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('144d7eb1-3600-4249-b593-44c4917c1fa8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_unpacked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80de5eb2-2fe0-4af4-9fe7-7ffe031ca8ff'), primary_key=True, serialize=False, unique=True),
        ),
    ]
