# Generated by Django 3.2.9 on 2022-01-28 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220124_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2a9dca8-be3e-4d3b-b991-6af9ce20b1a2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_packed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('469c7f97-1308-4de5-bd7e-22c5668f1847'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_unpacked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ab02d60-59f5-4a18-b8eb-d2e5122c59b3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
