# Generated by Django 3.2.9 on 2022-01-31 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('086a4e15-5e55-486b-871f-1cd775aaf0bb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_packed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84eefe8f-59e6-40d9-b705-50c5371f2840'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_unpacked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0facc2c6-ef8d-4cfe-9409-743ccd62ea0a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
