# Generated by Django 3.2.9 on 2022-02-01 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220131_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_packed',
            name='catagory',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery'), ('beverage', 'Beverage'), ('snacks', 'Snacks'), ('household', 'Household'), ('personalcare', 'Personal Care')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22909bf4-f405-4146-a547-53bd1706da88'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_packed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb1dd3ca-031f-4b9f-a4bf-9ee482631f65'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_unpacked',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d97510b2-2a80-46df-9e27-c24fc764be72'), primary_key=True, serialize=False, unique=True),
        ),
    ]
